# Generated by Django 3.2.9 on 2023-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_changepwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='lastPasswords',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='resetCode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
